/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Login.Login;
import javax.swing.JOptionPane;
import Modelo.Usuario;
/**
 *
 * @author Fernando
 */
public class frmPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        opcionesMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        usuarioMenu = new javax.swing.JMenu();
        alta_usuario_menu = new javax.swing.JMenuItem();
        baja_usuaio_menu = new javax.swing.JMenuItem();
        mod_datos_usuario_menu = new javax.swing.JMenuItem();
        AsignaturaMenu = new javax.swing.JMenu();
        alta_asignatura_menu = new javax.swing.JMenuItem();
        baja_asignatura_menu = new javax.swing.JMenuItem();
        mod_datos_asignatura_menu = new javax.swing.JMenuItem();
        matricular_alumno_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Software de Ventas"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(0, 115, 202));

        menuBar.setForeground(new java.awt.Color(0, 123, 247));

        opcionesMenu.setMnemonic('f');
        opcionesMenu.setText("Opciones");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuItemMouseClicked(evt);
            }
        });
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        opcionesMenu.add(exitMenuItem);

        menuBar.add(opcionesMenu);

        usuarioMenu.setMnemonic('e');
        usuarioMenu.setText("Usuario");

        alta_usuario_menu.setMnemonic('t');
        alta_usuario_menu.setText("Alta Usuario");
        usuarioMenu.add(alta_usuario_menu);

        baja_usuaio_menu.setText("Baja Usuario");
        usuarioMenu.add(baja_usuaio_menu);

        mod_datos_usuario_menu.setText("Modificar Datos Usuario");
        usuarioMenu.add(mod_datos_usuario_menu);

        menuBar.add(usuarioMenu);

        AsignaturaMenu.setMnemonic('h');
        AsignaturaMenu.setText("Asignatura");

        alta_asignatura_menu.setText("Alta asignatura");
        AsignaturaMenu.add(alta_asignatura_menu);

        baja_asignatura_menu.setText("Baja asignatura");
        AsignaturaMenu.add(baja_asignatura_menu);

        mod_datos_asignatura_menu.setText("Modificar datos asignatura");
        AsignaturaMenu.add(mod_datos_asignatura_menu);

        matricular_alumno_menu.setText("Matricular alumno");
        AsignaturaMenu.add(matricular_alumno_menu);

        menuBar.add(AsignaturaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void exitMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItemMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new frmPrincipalAdmin().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu AsignaturaMenu;
    public javax.swing.JMenuItem alta_asignatura_menu;
    public javax.swing.JMenuItem alta_usuario_menu;
    public javax.swing.JMenuItem baja_asignatura_menu;
    public javax.swing.JMenuItem baja_usuaio_menu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    public javax.swing.JMenuItem matricular_alumno_menu;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenuItem mod_datos_asignatura_menu;
    public javax.swing.JMenuItem mod_datos_usuario_menu;
    private javax.swing.JMenu opcionesMenu;
    public javax.swing.JMenu usuarioMenu;
    // End of variables declaration//GEN-END:variables

}
